name: contrastive-unpaired-translation
channels:
- peterjc123
- defaults
dependencies:
- python=3.6
- pytorch=1.1.0
- scipy
- pip:
  - dominate==2.4.0
  - git+https://github.com/pytorch/vision.git
  - Pillow==6.1.0
  - numpy==1.16.4
  - visdom==0.1.8
  - packaging
  - GPUtil==1.4.0
